#!/bin/bash
gamma=$1
tail -n 1 basrun.allene.$gamma.uniq.dat                        | awk '{printf "%15.8f %15.8f %8.3f %8.3f %8.3f %8.3f %8.3f %8.3f %8.3f %8.3f %8.3f %8.3f\n",$1,$2, $4,$5,$6, $7,$8,$9, $10,$11,$12,$13}'
tail -n 1 INC/basrun.allene.$gamma.uniq.dat                    | awk '{printf "%15.8f %15.8f %8.3f %8.3f %8.3f %8.3f %8.3f %8.3f %8.3f %8.3f %8.3f %8.3f\n",$1,$2, $4,$5,$6, $7,$8,$9, $10,$11,$12,$13}'
sort -k 1 -g -r  INC/INC3/basrun.allene.$gamma.dat | tail -n 1 | awk '{printf "%15.8f %15.8f %8.3f %8.3f %8.3f %8.3f %8.3f %8.3f %8.3f %8.3f %8.3f %8.3f\n",$1,$2, $4,$5,$6, $7,$8,$9, $10,$11,$12,$13}'

