#!/bin/bash
gamma=$1  
  
fbasrunlog="basrun."$gamma".log"
notconvfile="notconv."$gamma".dat"
brunallene="basrun.allene."$gamma".dat"
allene="allene."$gamma".dat"
basgmf="basdergmf."$gamma".log"
basfol="basderfol."$gamma".log"
paste $basgmf $basfol > "basrunGF."$gamma".log"

totalcall=`wc -l $notconvfile | awk '{print $1}'`
echo "total call (from $notconvfile):" $totalcall

totalcallnaprog=`grep NAPROG $notconvfile | wc -l | awk '{print $1}'`
totalcallnarmax=`grep NARMAX $notconvfile | wc -l | awk '{print $1}'`  
totalcallna=`grep NA $notconvfile | grep -v NAPROG | grep -v NARMAX | wc -l | awk '{print $1}'`  
totalcallok=`grep -v NA $notconvfile | wc -l | awk '{print $1}'`


echo "  total call NAPROG :" $totalcallnaprog
echo "  total call NARMAX :" $totalcallnarmax 
echo "  total call NA     :" $totalcallna
echo "  total call ok     :" $totalcallok
echo $totalcallnaprog $totalcallnarmax $totalcallna $totalcallok | awk '{print "CHECKTOT:",$1+$2+$3+$4}'

echo

brunok=` wc -l $brunallene | awk '{print $1}'`
echo " basrun pyt ok " $brunok

bderok=` wc -l $allene | awk '{print $1}'`  
echo " basrun der ok " $bderok


echo
for hhh in basrun*.$gamma.log; do 
echo $hhh

runcrycondtotal=`grep "runcrycond{" $hhh | wc -l | awk '{print $1}'`
echo "runcrycond total (from $hhh):" $runcrycondtotal

runcrycondok=`grep    "runcrycond{" $hhh  | grep " 0 " | wc -l | awk '{print $1}'`
echo "   runcrycond ok     :" $runcrycondok

runningcrys=`grep  "running crystal" $hhh  | wc -l| awk '{print $1}'`
echo "     new runs        :" $runningcrys 

outexisting=`grep  -A 1 "runcry{" $hhh | grep "getenefromout{" | wc -l| awk '{print $1}'`
echo "     outfile existing:" $outexisting

# this is a lot because eigs canbe not present
outnarmax=`grep -A 22 "runcrycond{" $hhh   | grep NARMAX | wc -l`
echo "     narmax:          " $outnarmax

echo $runningcrys $outexisting $outnarmax | awk '{print "   CHECKTOT", $1+$2+$3}' 

runcrycondone=`grep    "runcrycond{" $hhh  | grep " 1 " | wc -l | awk '{print $1}'`
runcrycondtwo=`grep    "runcrycond{" $hhh  | grep " 2 " | wc -l | awk '{print $1}'`   
runcrycondtre=`grep    "runcrycond{" $hhh  | grep " 3 " | wc -l | awk '{print $1}'`
runcrycondnaprog=`echo $runcrycondone   $runcrycondtwo  $runcrycondtre  | awk '{print $1+$2+$3}'`
runcrycondnaprogv=`grep -A 6 "runcrycond{" $hhh   | grep NAPROG | wc -l`
echo "  runcrycondnaprog : " $runcrycondnaprog " ==" $runcrycondnaprogv
echo "    runcrycond 1:" $runcrycondone
echo "    runcrycond 2:" $runcrycondtwo
echo "    runcrycond 3:" $runcrycondtre
echo
done



