#!/bin/bash
#gamma=0.002
gamma=$1

if [ ! -d INC3 ]; then
 mkdir INC3
 cp inputhf.d12.par INC3
 cp *.info INC3
 cp bmax.dat INC3
fi
awk '{print $1}' basrunsed.dat > tmpsed1
tail -n 1 basrun.allene.$gamma.uniq.dat  | awk '{ for (i=4;i<=NF; i++) {print $i} }' > tmpsed2
paste tmpsed1 tmpsed2 > INC3/basrunsed.dat
rm tmpsed1 tmpsed2

cd INC3
 pwd
 rm basrun.$gamma.log
 rm basderfol.$gamma.log
 rm basdergmf.$gamma.log
 rm notconv.$gamma.dat
 rm allene.$gamma.dat
 rm alleneder.$gamma.dat
 rm basrun.allene.$gamma.dat 

 export GMF="%4.2E"
 ~/DGBO/basderfol.sh 1
cd ..
